version: '3.7'

services:
  api:
    build:
      context: ./iclinic_api
    command: bash -c "python manage.py migrate && gunicorn iclinic_api.wsgi:application --bind 0.0.0.0:80 -t 120 --reload"
    container_name: api
    volumes:
      - ./iclinic_api:/app
    depends_on:
      - db
      - redis
    networks:
      - nginx
      - db
      - redis
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - api.env

  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db
    networks:
      - db
    env_file:
      - db.env
    restart: always
    ports:
      - "${DB_PORT}:5432"
    
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT}:81"
    networks:
      - nginx
    depends_on:
      - api
    restart: always

  redis:
    container_name: redis
    image: "redis:6.2.5-alpine"
    restart: always
    networks:
      - redis

volumes:
  postgres_data:

networks:
  nginx:
  db:
  redis: