# Generated by Django 3.2.7 on 2021-09-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clinic_id', models.PositiveIntegerField(db_column='clinic_id', null=True)),
                ('physician_id', models.PositiveIntegerField(db_column='physician_id')),
                ('patient_id', models.PositiveIntegerField(db_column='patient_id')),
                ('text', models.TextField()),
                ('metric_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'tb_prescription',
            },
        ),
    ]
